#线程数
NUMTHREAD=5

#Mongodb 参数
MONGO_URL='127.0.0.1'
MONGO_PORT=27017
MONGO_DB='news_list'
MONGO_TABLE='news_cla'

#elasticsearch 参数
ELASTICSEARCH_URL='127.0.0.1'
ELASTICSEARCH_PORT=9200
ELASTICSEARCH_NEWS_INDEX='my-news'
ELASTICSEARCH_NEWS_TYPE_OF_INFO='news-info'
ELASTICSEARCH_NEWS_TYPE_OF_LAST_TIME='news-last-time'

